# Generated by Django 4.0.3 on 2022-03-06 01:57

import uuid

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django_admin_geomap
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("trips", "0016_alter_tripproposal_options_and_more"),
        ("accounts", "0005_contactinformation_historicalcontactinformation"),
    ]

    operations = [
        migrations.CreateModel(
            name="TripRequestSearchLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "number_of_people",
                    models.PositiveSmallIntegerField(
                        db_index=True,
                        default=None,
                        null=True,
                        verbose_name="number of people",
                    ),
                ),
                (
                    "with_pets",
                    models.BooleanField(
                        db_index=True, default=None, null=True, verbose_name="with pets"
                    ),
                ),
                (
                    "luggage_size",
                    models.IntegerField(
                        db_index=True,
                        default=None,
                        null=True,
                        verbose_name="luggage size",
                    ),
                ),
                (
                    "point",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True,
                        geography=True,
                        null=True,
                        srid=4326,
                        verbose_name="point",
                    ),
                ),
                (
                    "area",
                    django.contrib.gis.db.models.fields.PolygonField(
                        blank=True,
                        geography=True,
                        null=True,
                        srid=4326,
                        verbose_name="area",
                    ),
                ),
                (
                    "radius",
                    models.IntegerField(
                        blank=True, db_index=True, null=True, verbose_name="radius"
                    ),
                ),
                (
                    "number_of_results",
                    models.PositiveIntegerField(
                        db_index=True, verbose_name="number of results"
                    ),
                ),
                (
                    "results",
                    models.ManyToManyField(
                        related_name="displays",
                        to="trips.triprequest",
                        verbose_name="results",
                    ),
                ),
                (
                    "spoken_languages",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        related_name="+",
                        to="accounts.language",
                        verbose_name="spoken languages",
                    ),
                ),
                (
                    "user_session",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logged_trip_search_requests",
                        to="accounts.usersession",
                        verbose_name="user session",
                    ),
                ),
            ],
            options={
                "verbose_name": "trip request search log",
                "verbose_name_plural": "trip request search logs",
                "ordering": ("-created_at",),
            },
            bases=(models.Model, django_admin_geomap.GeoItem),
        ),
    ]
