# Generated by Django 4.0.1 on 2022-03-02 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_usersession_language_historicallanguage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usersession",
            name="user",
        ),
    ]
