# Generated by Django 4.0.1 on 2022-03-03 09:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_usersession_language_historicallanguage"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersession",
            name="last_active_at",
            field=models.DateTimeField(
                auto_now=True, db_index=True, verbose_name="last active at"
            ),
        ),
        migrations.AddField(
            model_name="usersession",
            name="terms_accepted_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                default=django.utils.timezone.now,
                verbose_name="terms and conditions accepted at",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="usersession",
            name="id",
            field=models.CharField(
                max_length=255, primary_key=True, serialize=False, verbose_name="id"
            ),
        ),
    ]
