# Generated by Django 4.0.3 on 2022-03-07 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_historicallanguage_name_de_language_name_de'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinformation',
            name='first_name',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='contactinformation',
            name='last_name',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='historicalcontactinformation',
            name='first_name',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='historicalcontactinformation',
            name='last_name',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='last name'),
        ),
    ]
