# Generated by Django 4.0.1 on 2022-03-03 14:35

import uuid

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalArticle",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        verbose_name="updated at",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="name"
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        db_index=True, max_length=255, null=True, verbose_name="name"
                    ),
                ),
                (
                    "name_ru",
                    models.CharField(
                        db_index=True, max_length=255, null=True, verbose_name="name"
                    ),
                ),
                (
                    "name_uk",
                    models.CharField(
                        db_index=True, max_length=255, null=True, verbose_name="name"
                    ),
                ),
                (
                    "name_pl",
                    models.CharField(
                        db_index=True, max_length=255, null=True, verbose_name="name"
                    ),
                ),
                ("content", models.TextField()),
                ("content_en", models.TextField(null=True)),
                ("content_ru", models.TextField(null=True)),
                ("content_uk", models.TextField(null=True)),
                ("content_pl", models.TextField(null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField()),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical article",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": "history_date",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="updated at"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="name"
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        db_index=True, max_length=255, null=True, verbose_name="name"
                    ),
                ),
                (
                    "name_ru",
                    models.CharField(
                        db_index=True, max_length=255, null=True, verbose_name="name"
                    ),
                ),
                (
                    "name_uk",
                    models.CharField(
                        db_index=True, max_length=255, null=True, verbose_name="name"
                    ),
                ),
                (
                    "name_pl",
                    models.CharField(
                        db_index=True, max_length=255, null=True, verbose_name="name"
                    ),
                ),
                ("content", models.TextField()),
                ("content_en", models.TextField(null=True)),
                ("content_ru", models.TextField(null=True)),
                ("content_uk", models.TextField(null=True)),
                ("content_pl", models.TextField(null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
            ],
            options={
                "verbose_name": "article",
                "verbose_name_plural": "articles",
                "ordering": ("-created_at",),
            },
        ),
    ]
