# Generated by Django 4.0.3 on 2022-03-07 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content_de',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='name_de',
            field=models.CharField(db_index=True, max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='historicalarticle',
            name='content_de',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='historicalarticle',
            name='name_de',
            field=models.CharField(db_index=True, max_length=255, null=True, verbose_name='name'),
        ),
    ]
