# Generated by Django 4.0.3 on 2022-03-07 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_language_historicallanguage'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallanguage',
            name='name_de',
            field=models.CharField(db_index=True, max_length=128, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='language',
            name='name_de',
            field=models.CharField(db_index=True, max_length=128, null=True, verbose_name='name'),
        ),
    ]
