# Generated by Django 4.0.3 on 2022-03-07 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_historicallanguage_name_de_language_name_de'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='HistoricalLanguage',
        ),
        migrations.DeleteModel(
            name='Language',
        ),
    ]
