# Generated by Django 4.0.3 on 2022-03-08 20:52

import uuid

import packages.django.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "operations",
            "0004_remove_language_created_by_delete_historicallanguage_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        db_index=True,
                        default="",
                        max_length=254,
                        verbose_name="email",
                    ),
                ),
                (
                    "phone_number",
                    packages.django.db.fields.PhoneNumberField(
                        blank=True,
                        db_index=True,
                        default="",
                        max_length=16,
                        null=True,
                        verbose_name="phone number",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        max_length=64,
                        verbose_name="full name",
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        max_length=255,
                        verbose_name="subject",
                    ),
                ),
                ("content", models.TextField(verbose_name="content")),
                (
                    "was_read",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="was read"
                    ),
                ),
            ],
            options={
                "verbose_name": "message",
                "verbose_name_plural": "messages",
                "ordering": ("-created_at",),
            },
        ),
    ]
