# Generated by Django 4.0.3 on 2022-03-05 11:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("places", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="HistoricalPlaceCategory",
            new_name="HistoricalPOICategory",
        ),
        migrations.RenameModel(
            old_name="HistoricalPlace",
            new_name="HistoricalPointOfInterest",
        ),
        migrations.RenameModel(
            old_name="PlaceCategory",
            new_name="POICategory",
        ),
        migrations.RenameModel(
            old_name="Place",
            new_name="PointOfInterest",
        ),
        migrations.AlterModelOptions(
            name="historicalpointofinterest",
            options={
                "get_latest_by": "history_date",
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical point of interest",
            },
        ),
        migrations.AlterModelOptions(
            name="pointofinterest",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "point of interest",
                "verbose_name_plural": "points of interest",
            },
        ),
    ]
