# Generated by Django 4.0.3 on 2022-03-06 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_rename_historicalplacecategory_historicalpoicategory_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalpoicategory',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical place of interest category'},
        ),
        migrations.AlterModelOptions(
            name='poicategory',
            options={'verbose_name': 'place of interest category', 'verbose_name_plural': 'place of interest categories'},
        ),
    ]
