# Generated by Django 4.0.3 on 2022-03-06 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0004_remove_historicalpoicategory_id_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicalpoicategory",
            options={
                "get_latest_by": "history_date",
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical point of interest category",
            },
        ),
        migrations.AlterModelOptions(
            name="poicategory",
            options={
                "verbose_name": "point of interest category",
                "verbose_name_plural": "point of interest categories",
            },
        ),
        migrations.RemoveField(
            model_name="historicalpointofinterest",
            name="category",
        ),
        migrations.RemoveField(
            model_name="pointofinterest",
            name="category",
        ),
    ]
