# Generated by Django 4.0.3 on 2022-03-06 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0005_alter_historicalpoicategory_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalpointofinterest",
            name="category",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="places.poicategory",
                verbose_name="category",
            ),
        ),
        migrations.AddField(
            model_name="pointofinterest",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="places",
                to="places.poicategory",
                verbose_name="category",
            ),
        ),
    ]
