# Generated by Django 4.0.3 on 2022-03-07 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0008_alter_historicalpointofinterest_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalpoicategory",
            name="name",
            field=models.CharField(
                db_index=True, default="", max_length=255, verbose_name="name"
            ),
        ),
        migrations.AlterField(
            model_name="historicalpoicategory",
            name="name_en",
            field=models.CharField(
                db_index=True,
                default="",
                max_length=255,
                null=True,
                verbose_name="name",
            ),
        ),
        migrations.AlterField(
            model_name="historicalpoicategory",
            name="name_pl",
            field=models.CharField(
                db_index=True,
                default="",
                max_length=255,
                null=True,
                verbose_name="name",
            ),
        ),
        migrations.AlterField(
            model_name="historicalpoicategory",
            name="name_ru",
            field=models.CharField(
                db_index=True,
                default="",
                max_length=255,
                null=True,
                verbose_name="name",
            ),
        ),
        migrations.AlterField(
            model_name="historicalpoicategory",
            name="name_uk",
            field=models.CharField(
                db_index=True,
                default="",
                max_length=255,
                null=True,
                verbose_name="name",
            ),
        ),
        migrations.AlterField(
            model_name="poicategory",
            name="name",
            field=models.CharField(
                db_index=True, default="", max_length=255, verbose_name="name"
            ),
        ),
        migrations.AlterField(
            model_name="poicategory",
            name="name_en",
            field=models.CharField(
                db_index=True,
                default="",
                max_length=255,
                null=True,
                verbose_name="name",
            ),
        ),
        migrations.AlterField(
            model_name="poicategory",
            name="name_pl",
            field=models.CharField(
                db_index=True,
                default="",
                max_length=255,
                null=True,
                verbose_name="name",
            ),
        ),
        migrations.AlterField(
            model_name="poicategory",
            name="name_ru",
            field=models.CharField(
                db_index=True,
                default="",
                max_length=255,
                null=True,
                verbose_name="name",
            ),
        ),
        migrations.AlterField(
            model_name="poicategory",
            name="name_uk",
            field=models.CharField(
                db_index=True,
                default="",
                max_length=255,
                null=True,
                verbose_name="name",
            ),
        ),
    ]
