# Generated by Django 4.0.3 on 2022-03-07 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0009_alter_historicalpoicategory_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpoicategory',
            name='description_de',
            field=models.TextField(blank=True, default='', null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='historicalpoicategory',
            name='name_de',
            field=models.CharField(db_index=True, default='', max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='historicalpointofinterest',
            name='description_de',
            field=models.TextField(blank=True, default='', null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='historicalpointofinterest',
            name='name_de',
            field=models.CharField(db_index=True, default='', max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='poicategory',
            name='description_de',
            field=models.TextField(blank=True, default='', null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='poicategory',
            name='name_de',
            field=models.CharField(db_index=True, default='', max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='pointofinterest',
            name='description_de',
            field=models.TextField(blank=True, default='', null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='pointofinterest',
            name='name_de',
            field=models.CharField(db_index=True, default='', max_length=255, null=True, verbose_name='name'),
        ),
    ]
