# Generated by Django 4.0.3 on 2022-03-07 14:23

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("places", "0010_historicalpoicategory_description_de_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalCountry",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        verbose_name="updated at",
                    ),
                ),
                (
                    "code",
                    models.CharField(db_index=True, max_length=2, verbose_name="code"),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="name"
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        db_index=True, max_length=255, null=True, verbose_name="name"
                    ),
                ),
                (
                    "name_ru",
                    models.CharField(
                        db_index=True, max_length=255, null=True, verbose_name="name"
                    ),
                ),
                (
                    "name_uk",
                    models.CharField(
                        db_index=True, max_length=255, null=True, verbose_name="name"
                    ),
                ),
                (
                    "name_pl",
                    models.CharField(
                        db_index=True, max_length=255, null=True, verbose_name="name"
                    ),
                ),
                (
                    "name_de",
                    models.CharField(
                        db_index=True, max_length=255, null=True, verbose_name="name"
                    ),
                ),
                (
                    "territory",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        geography=True, srid=4326, verbose_name="territory"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField()),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical country",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": "history_date",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="updated at"
                    ),
                ),
                (
                    "code",
                    models.CharField(db_index=True, max_length=2, verbose_name="code"),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="name"
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        db_index=True, max_length=255, null=True, verbose_name="name"
                    ),
                ),
                (
                    "name_ru",
                    models.CharField(
                        db_index=True, max_length=255, null=True, verbose_name="name"
                    ),
                ),
                (
                    "name_uk",
                    models.CharField(
                        db_index=True, max_length=255, null=True, verbose_name="name"
                    ),
                ),
                (
                    "name_pl",
                    models.CharField(
                        db_index=True, max_length=255, null=True, verbose_name="name"
                    ),
                ),
                (
                    "name_de",
                    models.CharField(
                        db_index=True, max_length=255, null=True, verbose_name="name"
                    ),
                ),
                (
                    "territory",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        geography=True, srid=4326, verbose_name="territory"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
            ],
            options={
                "verbose_name": "country",
                "verbose_name_plural": "countries",
                "ordering": ("code",),
            },
        ),
    ]
