# Generated by Django 4.0.3 on 2022-03-07 17:54

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0011_historicalcountry_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="country",
            name="code",
            field=models.CharField(db_index=True, max_length=3, verbose_name="code"),
        ),
        migrations.AlterField(
            model_name="country",
            name="territory",
            field=django.contrib.gis.db.models.fields.GeometryCollectionField(
                geography=True, srid=4326, verbose_name="territory"
            ),
        ),
        migrations.AlterField(
            model_name="historicalcountry",
            name="code",
            field=models.CharField(db_index=True, max_length=3, verbose_name="code"),
        ),
        migrations.AlterField(
            model_name="historicalcountry",
            name="territory",
            field=django.contrib.gis.db.models.fields.GeometryCollectionField(
                geography=True, srid=4326, verbose_name="territory"
            ),
        ),
    ]
