# Generated by Django 4.0.3 on 2022-03-07 17:57

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0012_alter_country_code_alter_country_territory_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="country",
            name="territory",
            field=django.contrib.gis.db.models.fields.MultiPolygonField(
                geography=True, srid=4326, verbose_name="territory"
            ),
        ),
        migrations.AlterField(
            model_name="historicalcountry",
            name="territory",
            field=django.contrib.gis.db.models.fields.MultiPolygonField(
                geography=True, srid=4326, verbose_name="territory"
            ),
        ),
    ]
