# Generated by Django 4.0.3 on 2022-03-07 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0013_alter_country_territory_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalcountry",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="historicalcountry",
            name="history_user",
        ),
        migrations.DeleteModel(
            name="Country",
        ),
        migrations.DeleteModel(
            name="HistoricalCountry",
        ),
    ]
