# Generated by Django 4.0.3 on 2022-03-07 23:38

from django.db import migrations, transaction


@transaction.atomic
def add_countries_to_waypoints_fwd(apps, schema_editor):
    WayPoint = apps.get_model("trips", "WayPoint")
    Country = apps.get_model("places", "Country")

    for waypoint in WayPoint.objects.all():
        waypoint.country = Country.objects.filter(territory__covers=waypoint.point).first()
        waypoint.save(update_fields=["country"])


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0015_historicalcountry_country'),
    ]

    operations = [
        migrations.RunPython(
            add_countries_to_waypoints_fwd,
            migrations.RunPython.noop
        )
    ]
