# Generated by Django 4.0.1 on 2022-03-02 18:07

import uuid

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicaltriprequest",
            name="from_point",
        ),
        migrations.RemoveField(
            model_name="historicaltriprequest",
            name="to_point",
        ),
        migrations.RemoveField(
            model_name="triprequest",
            name="from_point",
        ),
        migrations.RemoveField(
            model_name="triprequest",
            name="to_point",
        ),
        migrations.CreateModel(
            name="WayPoint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        db_index=True, verbose_name="order"
                    ),
                ),
                (
                    "point",
                    django.contrib.gis.db.models.fields.PointField(
                        geography=True, srid=4326, verbose_name="to point"
                    ),
                ),
                (
                    "trip_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="waypoints",
                        to="trips.triprequest",
                        verbose_name="trip request",
                    ),
                ),
            ],
            options={
                "verbose_name": "waypoint",
                "verbose_name_plural": "waypoints",
                "ordering": ("order",),
                "unique_together": {("order", "trip_request")},
            },
        ),
    ]
