# Generated by Django 4.0.1 on 2022-03-03 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_usersession_last_active_at_and_more"),
        ("trips", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaltriprequest",
            name="last_active_at",
            field=models.DateTimeField(
                blank=True, db_index=True, editable=False, verbose_name="last active at"
            ),
        ),
        migrations.AlterField(
            model_name="historicaltriprequest",
            name="user_session",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="accounts.usersession",
                verbose_name="user session",
            ),
        ),
        migrations.AlterField(
            model_name="triprequest",
            name="last_active_at",
            field=models.DateTimeField(
                auto_now=True, db_index=True, verbose_name="last active at"
            ),
        ),
        migrations.AlterField(
            model_name="triprequest",
            name="user_session",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_trip_requests",
                to="accounts.usersession",
                verbose_name="user session",
            ),
        ),
    ]
