# Generated by Django 4.0.1 on 2022-03-02 18:51

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0002_remove_historicaltriprequest_from_point_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="waypoint",
            name="point",
            field=django.contrib.gis.db.models.fields.PointField(
                geography=True, srid=4326, verbose_name="point"
            ),
        ),
    ]
