# Generated by Django 4.0.1 on 2022-03-03 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0002_alter_historicaltriprequest_last_active_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="triprequest",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, db_index=True, verbose_name="updated at"
            ),
        ),
    ]
