# Generated by Django 4.0.3 on 2022-03-04 21:38

import uuid

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("trips", "0004_alter_triprequest_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicaltriprequest",
            options={
                "get_latest_by": "history_date",
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical trip request",
            },
        ),
        migrations.AlterModelOptions(
            name="triprequest",
            options={
                "ordering": ("-trip__route_length", "-created_at"),
                "verbose_name": "trip request",
                "verbose_name_plural": "trip requests",
            },
        ),
        migrations.AddField(
            model_name="historicaltriprequest",
            name="allow_partial_trip",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="allow partial trip"
            ),
        ),
        migrations.AddField(
            model_name="triprequest",
            name="allow_partial_trip",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="allow partial trip"
            ),
        ),
        migrations.AlterField(
            model_name="historicaltriprequest",
            name="route_length",
            field=models.FloatField(
                db_index=True, null=True, verbose_name="route_length"
            ),
        ),
        migrations.AlterField(
            model_name="historicaltriprequest",
            name="state",
            field=models.CharField(
                choices=[
                    ("active", "active"),
                    ("cancelled", "cancelled"),
                    ("completed", "completed"),
                    ("outdated", "outdated"),
                    ("invalid", "invalid"),
                ],
                db_index=True,
                default="active",
                max_length=32,
                verbose_name="state",
            ),
        ),
        migrations.AlterField(
            model_name="triprequest",
            name="route_length",
            field=models.FloatField(
                db_index=True, null=True, verbose_name="route_length"
            ),
        ),
        migrations.AlterField(
            model_name="triprequest",
            name="state",
            field=models.CharField(
                choices=[
                    ("active", "active"),
                    ("cancelled", "cancelled"),
                    ("completed", "completed"),
                    ("outdated", "outdated"),
                    ("invalid", "invalid"),
                ],
                db_index=True,
                default="active",
                max_length=32,
                verbose_name="state",
            ),
        ),
        migrations.AlterField(
            model_name="waypoint",
            name="trip_request",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="waypoints",
                to="trips.triprequest",
                verbose_name="trip request",
            ),
        ),
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="updated at"
                    ),
                ),
                (
                    "route",
                    django.contrib.gis.db.models.fields.LineStringField(
                        blank=True,
                        geography=True,
                        null=True,
                        srid=4326,
                        verbose_name="route",
                    ),
                ),
                (
                    "route_length",
                    models.FloatField(
                        db_index=True, null=True, verbose_name="route length"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_trips",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
            ],
            options={
                "verbose_name": "trip",
                "verbose_name_plural": "trips",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="HistoricalTrip",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        verbose_name="updated at",
                    ),
                ),
                (
                    "route",
                    django.contrib.gis.db.models.fields.LineStringField(
                        blank=True,
                        geography=True,
                        null=True,
                        srid=4326,
                        verbose_name="route",
                    ),
                ),
                (
                    "route_length",
                    models.FloatField(
                        db_index=True, null=True, verbose_name="route length"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField()),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical trip",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": "history_date",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AlterUniqueTogether(
            name="waypoint",
            unique_together={("order", "trip_request")},
        ),
        migrations.AddField(
            model_name="historicaltriprequest",
            name="trip",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="trips.trip",
                verbose_name="trip",
            ),
        ),
        migrations.AddField(
            model_name="triprequest",
            name="trip",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trip_request",
                to="trips.trip",
                verbose_name="trip",
            ),
        ),
        migrations.AddField(
            model_name="waypoint",
            name="trip",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="waypoints",
                to="trips.trip",
                verbose_name="trip",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="waypoint",
            unique_together={("order", "trip_request"), ("order", "trip")},
        ),
    ]
