# Generated by Django 4.0.1 on 2022-03-02 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0004_historicaltriprequest_last_active_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaltriprequest",
            name="luggage_size",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "small bags"), (2, "large bags"), (3, "cargo")],
                db_index=True,
                default=1,
                verbose_name="luggage size",
            ),
        ),
        migrations.AlterField(
            model_name="triprequest",
            name="luggage_size",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "small bags"), (2, "large bags"), (3, "cargo")],
                db_index=True,
                default=1,
                verbose_name="luggage size",
            ),
        ),
    ]
