# Generated by Django 4.0.3 on 2022-03-04 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0008_auto_20220304_2259"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="waypoint",
            unique_together={("order", "trip")},
        ),
        migrations.RemoveField(
            model_name="historicaltriprequest",
            name="route_length",
        ),
        migrations.RemoveField(
            model_name="triprequest",
            name="route_length",
        ),
        migrations.RemoveField(
            model_name="waypoint",
            name="trip_request",
        ),
    ]
