# Generated by Django 4.0.3 on 2022-03-05 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_historicaluser_password_alter_user_password"),
        ("trips", "0009_alter_waypoint_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaltriprequest",
            name="user_session",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="accounts.usersession",
                verbose_name="user session",
            ),
        ),
        migrations.AlterField(
            model_name="triprequest",
            name="user_session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_trip_requests",
                to="accounts.usersession",
                verbose_name="user session",
            ),
        ),
    ]
