# Generated by Django 4.0.3 on 2022-03-06 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0009_alter_waypoint_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltriprequest',
            name='is_verified',
            field=models.BooleanField(db_index=True, default=False, verbose_name='is verified'),
        ),
        migrations.AddField(
            model_name='triprequest',
            name='is_verified',
            field=models.BooleanField(db_index=True, default=False, verbose_name='is verified'),
        ),
    ]
