# Generated by Django 4.0.3 on 2022-03-05 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0012_triprequestsearchlog_number_of_results"),
    ]

    operations = [
        migrations.AlterField(
            model_name="triprequestsearchlog",
            name="with_pets",
            field=models.BooleanField(
                db_index=True, default=None, null=True, verbose_name="with pets"
            ),
        ),
    ]
