# Generated by Django 4.0.3 on 2022-03-05 22:24

import uuid

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django_admin_geomap
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_contactinformation_historicalcontactinformation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("trips", "0014_triprequestsearchlog_results"),
    ]

    operations = [
        migrations.CreateModel(
            name="TripProposal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="updated at"
                    ),
                ),
                (
                    "departure_time",
                    models.DateTimeField(db_index=True, verbose_name="start time"),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("active", "active"),
                            ("cancelled", "cancelled"),
                            ("completed", "completed"),
                            ("outdated", "outdated"),
                            ("invalid", "invalid"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=32,
                        verbose_name="state",
                    ),
                ),
                (
                    "number_of_seats",
                    models.PositiveSmallIntegerField(
                        db_index=True, default=4, verbose_name="number of seats"
                    ),
                ),
                (
                    "pets_allowed",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="pets allowed"
                    ),
                ),
                (
                    "luggage_carrier_size",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "small bags"), (2, "large bags"), (3, "cargo")],
                        db_index=True,
                        default=1,
                        verbose_name="luggage carrier size",
                    ),
                ),
                ("comment", models.TextField(verbose_name="comment")),
                (
                    "starting_point",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True,
                        geography=True,
                        null=True,
                        srid=4326,
                        verbose_name="point",
                    ),
                ),
                (
                    "contact_information",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="accounts.contactinformation",
                        verbose_name="contact information",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_trip_proposals",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "spoken_languages",
                    models.ManyToManyField(
                        related_name="+",
                        to="accounts.language",
                        verbose_name="spoken languages",
                    ),
                ),
                (
                    "trip",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trip_proposal",
                        to="trips.trip",
                        verbose_name="trip",
                    ),
                ),
                (
                    "user_session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_trip_proposals",
                        to="accounts.usersession",
                        verbose_name="user session",
                    ),
                ),
            ],
            options={
                "verbose_name": "trip proposal",
                "verbose_name_plural": "trip proposals",
                "ordering": ("-created_at",),
            },
            bases=(models.Model, django_admin_geomap.GeoItem),
        ),
        migrations.CreateModel(
            name="HistoricalTripProposal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        verbose_name="updated at",
                    ),
                ),
                (
                    "departure_time",
                    models.DateTimeField(db_index=True, verbose_name="start time"),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("active", "active"),
                            ("cancelled", "cancelled"),
                            ("completed", "completed"),
                            ("outdated", "outdated"),
                            ("invalid", "invalid"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=32,
                        verbose_name="state",
                    ),
                ),
                (
                    "number_of_seats",
                    models.PositiveSmallIntegerField(
                        db_index=True, default=4, verbose_name="number of seats"
                    ),
                ),
                (
                    "pets_allowed",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="pets allowed"
                    ),
                ),
                (
                    "luggage_carrier_size",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "small bags"), (2, "large bags"), (3, "cargo")],
                        db_index=True,
                        default=1,
                        verbose_name="luggage carrier size",
                    ),
                ),
                ("comment", models.TextField(verbose_name="comment")),
                (
                    "starting_point",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True,
                        geography=True,
                        null=True,
                        srid=4326,
                        verbose_name="point",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField()),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "contact_information",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="accounts.contactinformation",
                        verbose_name="contact information",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="trips.trip",
                        verbose_name="trip",
                    ),
                ),
                (
                    "user_session",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="accounts.usersession",
                        verbose_name="user session",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical trip proposal",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": "history_date",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
