# Generated by Django 4.0.3 on 2022-03-06 09:32

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0016_alter_tripproposal_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TripRequestReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("was_not_found", "transport was not found"),
                            ("not_required", "transport not required"),
                            ("found_on_platform", "transport was found on platform"),
                            (
                                "found_in_other_place",
                                "transport was found in other place",
                            ),
                        ],
                        db_index=True,
                        default="",
                        max_length=32,
                        verbose_name="result",
                    ),
                ),
                (
                    "satisfaction_rate",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "disappointed"),
                            (1, "not satisfied"),
                            (3, "rather satisfied"),
                            (4, "satisfied"),
                            (5, "admired"),
                        ],
                        db_index=True,
                        null=True,
                        verbose_name="satisfaction rate",
                    ),
                ),
                (
                    "trip_request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report",
                        to="trips.triprequest",
                        verbose_name="trip request",
                    ),
                ),
            ],
            options={
                "verbose_name": "trip request report",
                "verbose_name_plural": "trip request reports",
                "ordering": ("-created_at",),
            },
        ),
    ]
