# Generated by Django 4.0.3 on 2022-03-07 13:02

import apps.trips.models.trip_requests
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0018_historicaltriprequest_is_verified_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaltriprequest",
            name="active_until",
            field=models.DateTimeField(
                db_index=True,
                default=apps.trips.models.trip_requests.get_default_active_until,
                verbose_name="active until",
            ),
        ),
        migrations.AddField(
            model_name="triprequest",
            name="active_until",
            field=models.DateTimeField(
                db_index=True,
                default=apps.trips.models.trip_requests.get_default_active_until,
                verbose_name="active until",
            ),
        ),
    ]
