# Generated by Django 4.0.3 on 2022-03-07 13:02

from django.db import migrations, transaction
from django.utils import timezone


@transaction.atomic
def update_active_until_time_for_requested_trips_fwd(apps, schema_editor):
    TripRequest = apps.get_model("trips", "TripRequest")

    for trip_request in TripRequest.objects.all():
        trip_request.active_until = trip_request.last_active_at + timezone.timedelta(
            days=1
        )
        trip_request.save(update_fields=["active_until", "updated_at"])


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0019_historicaltriprequest_active_until_and_more"),
    ]

    operations = [
        migrations.RunPython(
            update_active_until_time_for_requested_trips_fwd, migrations.RunPython.noop
        )
    ]
