# Generated by Django 4.0.3 on 2022-03-07 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0020_auto_20220307_1302"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="triprequest",
            options={
                "ordering": ("-trip__route_length", "-updated_at"),
                "verbose_name": "trip request",
                "verbose_name_plural": "trip requests",
            },
        ),
    ]
