# Generated by Django 4.0.3 on 2022-03-07 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_contactinformation_first_name_and_more'),
        ('trips', '0022_historicaltriprequest_contact_information_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triprequest',
            name='contact_information',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.contactinformation', verbose_name='contact_information'),
        ),
    ]
