# Generated by Django 4.0.3 on 2022-03-07 19:13

import packages.django.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0023_alter_triprequest_contact_information"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicaltriprequest",
            name="contact_information",
        ),
        migrations.RemoveField(
            model_name="triprequest",
            name="contact_information",
        ),
        migrations.AddField(
            model_name="historicaltriprequest",
            name="phone_number",
            field=packages.django.db.fields.PhoneNumberField(
                blank=True,
                db_index=True,
                max_length=16,
                null=True,
                verbose_name="phone number",
            ),
        ),
        migrations.AddField(
            model_name="triprequest",
            name="phone_number",
            field=packages.django.db.fields.PhoneNumberField(
                blank=True,
                db_index=True,
                max_length=16,
                null=True,
                verbose_name="phone number",
            ),
        ),
    ]
