# Generated by Django 4.0.3 on 2022-03-07 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0015_historicalcountry_country'),
        ('trips', '0024_remove_historicaltriprequest_contact_information_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='waypoint',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waypoints', to='places.country', verbose_name='country'),
        ),
    ]
